"""PostgreSQL v2 data access package."""

from .base import Base, metadata
from .config import DatabaseConfigurationError, DatabaseSettings
from .connection import Database
from .models import (
    Account,
    AccountUser,
    ApiToken,
    AuditLog,
    BrandingProfile,
    Category,
    ContentCategory,
    ContentFingerprint,
    ContentItem,
    ContentMedia,
    ContentSourceRef,
    DeduplicationProfile,
    Destination,
    FilterProfile,
    Project,
    ProjectCategory,
    PublicationAttempt,
    PublishedMessage,
    PublishJob,
    RetentionPolicy,
    Role,
    ScheduleProfile,
    Source,
    SourceCheckpoint,
    SourceRoute,
    SystemEvent,
    TelegramAccount,
    TelegramSession,
    TransformProfile,
    User,
    UserSession,
    WorkerLease,
)
from .repositories import (
    AccountRepository,
    DestinationRepository,
    ProjectRepository,
    SourceRepository,
    SourceRouteRepository,
)

__all__ = [
    "Account",
    "AccountUser",
    "AccountRepository",
    "ApiToken",
    "AuditLog",
    "Base",
    "BrandingProfile",
    "Category",
    "ContentCategory",
    "ContentFingerprint",
    "ContentItem",
    "ContentMedia",
    "ContentSourceRef",
    "Database",
    "DatabaseConfigurationError",
    "DatabaseSettings",
    "DeduplicationProfile",
    "Destination",
    "DestinationRepository",
    "FilterProfile",
    "Project",
    "ProjectRepository",
    "ProjectCategory",
    "PublicationAttempt",
    "PublishedMessage",
    "PublishJob",
    "RetentionPolicy",
    "Role",
    "ScheduleProfile",
    "Source",
    "SourceRepository",
    "SourceCheckpoint",
    "SourceRoute",
    "SourceRouteRepository",
    "SystemEvent",
    "TelegramAccount",
    "TelegramSession",
    "TransformProfile",
    "User",
    "UserSession",
    "WorkerLease",
    "metadata",
]
